# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aac059ba0b0f2ff8d48c124a23340823a0e88881efde27c34b560d8c953b65391ed68f21298dbe96097ed4f70b8205986db6d46f4e3dcdfbd9d0760cb4e7bb38

test:
  secret_key_base: 2760520a86ecf1926eed56d4a9d80983ca1548c46d35de7582291e9f7e7ca5e58dcdaff2a6e3506144ff8eae9118e710ed9fc0b3be9df832342edebecb426abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
